spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic
    username: clinic
    password: clinic
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    token:
      secret: 'thiago'


app:
  tenant:
    resolution: subdomain # fallback: header X-Tenant-ID
